import "./globals.css";
import { Toaster } from "@/Components/ui/toaster";

export const metadata = {
  title: "Ainda não sei",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={` antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
